import fs from 'fs/promises'

(async () => {

  await fs.rm('./dist', {
    recursive: true,
    force: true
  })

  await fs.mkdir('./dist')

  await fs.writeFile('./dist/index.html', `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Static site generated by Node</title>
    </head>
    <body>
        <h1>Welcome!</h1>
        <p>This is a generated static site.</p>
        <p>${new Date().toLocaleTimeString()}</p>
    </body>
    </html>
    `)

})();
